apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name:coffee-order-workflow-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: coffee-order-workflow.kogito
      http:
        paths:
          - path: /
            backend:
              serviceName: coffee-order-workflow
              servicePort: 80