apiVersion: app.kiegroup.org/v1beta1
kind: KogitoBuild
metadata:
  name: coffee-shop
spec:
  type: RemoteSource
  gitSource:
    contextDir: coffee-shop
    uri: 'https://github.com/rtalakanti/training'
---
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  name: coffee-shop
spec:
  replicas: 1
  probes:
    livenessProbe:
      httpGet:
        path: /probes/live # Liveness endpoint
        port: 8080
    readinessProbe:
      httpGet:
        path: /probes/ready # Readiness endpoint
        port: 8080
    startupProbe:
      tcpSocket:
        port: 8080