apiVersion: app.kiegroup.org/v1beta1
kind: KogitoInfra
metadata:
  name: kogito-knative-infra
spec:
  # bind Knative Broker with our own service
  resource:
    apiVersion: eventing.knative.dev/v1
    kind: Broker
    name: default
---
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoBuild
metadata:
  name: order-processing-workflow
spec:
  type: RemoteSource
  gitSource:
    contextDir: serverless-workflow-order-processing
    uri: 'https://github.com/rtalakanti/training'

---
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  name: order-processing-workflow
spec:
  replicas: 1
  # we bind our application with Knative env
  infra:
    - kogito-knative-infra
